version: '3.9'

services:
  web:
    build: ./
    environment:
      - APACHE_RUN_USER=#1000
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./:/var/www/html
    ports:
      - 10097:80
    working_dir: /var/www/html

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: mariadb
    #restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studens-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 11097:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
    driver: local
  rabbitmq_data:


